"""add_patient_details_to_booking

Revision ID: 22a252c39bde
Revises: 5db74e726f14
Create Date: 2026-01-13 15:21:49.281362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a252c39bde'
down_revision: Union[str, None] = '5db74e726f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_booking', sa.Column('patient_name', sa.String(), nullable=True))
    op.add_column('tbl_booking', sa.Column('patient_age', sa.String(), nullable=True))
    op.add_column('tbl_booking', sa.Column('patient_gender', sa.String(), nullable=True))
    op.add_column('tbl_booking', sa.Column('patient_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_booking', 'patient_notes')
    op.drop_column('tbl_booking', 'patient_gender')
    op.drop_column('tbl_booking', 'patient_age')
    op.drop_column('tbl_booking', 'patient_name')
    # ### end Alembic commands ###

