"""add cascade delete to service pricing

Revision ID: 5db74e726f14
Revises: 5e16780d705f
Create Date: 2026-01-12 21:12:39.885838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db74e726f14'
down_revision: Union[str, None] = '5e16780d705f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tbl_service_pricing_service_id_fkey'), 'tbl_service_pricing', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_service_pricing', 'tbl_service', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_service_pricing', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_service_pricing_service_id_fkey'), 'tbl_service_pricing', 'tbl_service', ['service_id'], ['id'])
    # ### end Alembic commands ###

