"""add_patient_phone_to_booking

Revision ID: ba3a87982f7d
Revises: 22a252c39bde
Create Date: 2026-01-13 15:29:25.960557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3a87982f7d'
down_revision: Union[str, None] = '22a252c39bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_booking', sa.Column('patient_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_booking', 'patient_phone')
    # ### end Alembic commands ###

